CREATE TABLE employees(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(25) NOT NULL,
    last_name varchar(25) NOT NULL,
    email varchar(30) NOT NULL UNIQUE,
    phone_number varchar(50) NOT NULL UNIQUE,
    salary FLOAT NOT NULL,
    department_id BIGINT NOT NULL,
    FOREIGN KEY (department_id) REFERENCES departments (id)
);

ALTER TABLE employees
    ADD CONSTRAINT first_name_not_empty CHECK (first_name <> ''),
    ADD CONSTRAINT first_name_not_blanc CHECK (first_name !~ '^\s*$'),
    ADD CONSTRAINT last_name_not_empty CHECK (last_name <> ''),
    ADD CONSTRAINT last_name_not_blanc CHECK (last_name !~ '^\s*$'),
    ADD CONSTRAINT email_not_empty CHECK (email <> ''),
    ADD CONSTRAINT email_not_blanc CHECK (email !~ '^\s*$'),
    ADD CONSTRAINT phone_number_not_empty CHECK (phone_number <> ''),
    ADD CONSTRAINT phone_number_not_blanc CHECK (phone_number !~ '^\s*$'),
    ADD CONSTRAINT salary_more_than_one CHECK (salary >= 1.0);